import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
    try {
        const { blocks, date } = await req.json();
        if (!blocks || !date) {
            return NextResponse.json({ error: 'Missing blocks or date' }, { status: 400 });
        }
        const { getCalendarManager } = await import('@/lib/calendar-manager');
        const manager = await getCalendarManager();
        let pushed = 0;
        const errors: string[] = [];
        for (const block of blocks) {
            try {
                await manager.createEvent({
                    title: block.title,
                    startTime: `${date}T${block.start}:00`,
                    endTime: `${date}T${block.end}:00`,
                    allDay: false,
                    editable: true,
                    description: 'Generated by Skales Planner AI',
                });
                pushed++;
            } catch (e: any) {
                errors.push(`${block.title}: ${e.message}`);
            }
        }
        return NextResponse.json({ pushed, errors });
    } catch (e: any) {
        return NextResponse.json({ error: e.message }, { status: 500 });
    }
}
