/**
 * POST /api/chat/telegram/approval
 *
 * Called by telegram-bot.js when the user taps Approve / Deny on
 * an inline keyboard generated by the Telegram approval flow.
 *
 * Body: { approvalId: string, decision: 'approve' | 'deny' }
 *
 * Flow:
 *   1. Load the pending approval from disk
 *   2a. Approve → re-run agentExecute with confirmedToolCallIds
 *   2b. Deny    → push friendly denial message to session
 *   3. Return final text so telegram-bot.js can send it to the user
 */

import { NextRequest, NextResponse } from 'next/server';
import { loadSession, saveSession, type ChatMessage } from '@/actions/chat';
import { agentExecute } from '@/actions/orchestrator';
import { loadApproval, deleteApproval } from '@/lib/approval-store';

export const dynamic    = 'force-dynamic';
export const revalidate = 0;

export async function POST(req: NextRequest) {
    try {
        const { approvalId, decision } = await req.json() as {
            approvalId: string;
            decision:   'approve' | 'deny';
        };

        if (!approvalId || !decision) {
            return NextResponse.json({ success: false, error: 'Missing approvalId or decision' }, { status: 400 });
        }

        const pending = loadApproval(approvalId);
        if (!pending) {
            return NextResponse.json({
                success: false,
                error:   'Approval request expired or not found (> 30 min).',
                response: '⏰ This approval request has expired. Please send your message again.',
            });
        }

        // Clean up regardless of decision
        deleteApproval(approvalId);

        const session = pending.sessionId ? await loadSession(pending.sessionId) : null;

        // ── DENY ──────────────────────────────────────────────────────────────
        if (decision === 'deny') {
            const denyMsg = '❌ Got it — action cancelled. Let me know if you want to try something else!';
            if (session) {
                session.messages.push({
                    role:      'assistant',
                    content:   denyMsg,
                    timestamp: Date.now(),
                } as ChatMessage);
                await saveSession(session);
            }
            return NextResponse.json({ success: true, response: denyMsg });
        }

        // ── APPROVE ───────────────────────────────────────────────────────────
        const confirmedIds = pending.toolCalls.map(tc => tc.id);

        let toolResults: any[] = [];
        try {
            toolResults = await agentExecute(pending.toolCalls, confirmedIds);
        } catch (e: any) {
            return NextResponse.json({
                success:  false,
                response: `⚠️ Error executing approved action: ${e?.message ?? 'Unknown error'}`,
            });
        }

        // Build summary message from tool results
        const summaries: string[] = toolResults.map(r => {
            if (r.displayMessage) return r.displayMessage;
            if (r.result?.message) return r.result.message;
            if (r.success === false) return `❌ ${r.toolName}: failed`;
            return `✅ ${r.toolName}: done`;
        });

        const response = summaries.join('\n') || '✅ Actions completed successfully.';

        // Persist tool messages back to session
        if (session && toolResults.length > 0) {
            for (let i = 0; i < toolResults.length; i++) {
                const res = toolResults[i];
                const toolMsg: ChatMessage = {
                    role:          'tool',
                    content:       JSON.stringify(res.result),
                    tool_call_id:  pending.toolCalls[i]?.id,
                    name:          pending.toolCalls[i]?.function?.name,
                    display_message: res.displayMessage,
                    timestamp:     Date.now(),
                } as any;
                session.messages.push(toolMsg);
            }

            // BUG 1 FIX: Do NOT re-enter the agent loop after approval execution.
            // Previously we called agentDecide() here which could trigger another
            // tool call -> another approval -> infinite loop. Instead, just confirm
            // "Done." with the raw tool result summary.
            session.messages.push({
                role:      'assistant',
                content:   response,
                timestamp: Date.now(),
            } as ChatMessage);
            await saveSession(session);
        }

        return NextResponse.json({ success: true, response });

    } catch (err: any) {
        console.error('[TelegramApproval] Error:', err);
        return NextResponse.json({ success: false, error: err?.message }, { status: 500 });
    }
}
