'use server';

/**
 * Skales — Autopilot Server Actions (Phase 5)
 *
 * Covers:
 *   A) User Profile / Identity & Memory — read/write user_profile.json
 *   B) Log management — getLogs, clearLogs
 *   C) Deep-Dive Interview — guided LLM conversation → saves to profile
 *   D) Capability Matching & Master Plan generation → pushes tasks to tasks.json
 *   E) Daily Stand-up report generation
 *   F) Task CRUD wrappers for the UI (add, edit, cancel, prioritize)
 *
 * Data locations (all under DATA_DIR):
 *   user_profile.json  — long-term memory about the user's goals
 *   autopilot_logs.json — append-only action log
 *   tasks.json         — the task state machine
 */

import fs   from 'fs';
import path from 'path';
import { DATA_DIR } from '@/lib/paths';
import {
    createTask, updateTask, deleteTask, cancelTask,
    getAllTasks, getTaskStats,
    type TaskPriority, type AgentTask,
} from '@/lib/agent-tasks';
import { getLogs, clearLogs as _clearLogs, type AutopilotLogEntry } from '@/lib/autopilot-logger';
import { loadSettings } from '@/actions/chat';

const PROFILE_FILE = path.join(DATA_DIR, 'user_profile.json');

// ─── Types ───────────────────────────────────────────────────────────────────

export interface UserProfile {
    /** What the user is ultimately trying to achieve */
    primaryGoal?: string;
    /** Business/personal niche */
    niche?: string;
    /** Available budget / resources */
    budget?: string;
    /** Key constraints (time, legal, technical) */
    constraints?: string;
    /** Anything else Skales should know long-term */
    additionalContext?: string;
    /** The raw strategy/roadmap generated by the last planning session */
    masterPlan?: string;
    /** Title of the current master plan */
    masterPlanTitle?: string;
    /** History of previous roadmaps (newest first, max 10) */
    roadmapHistory?: Array<{ roadmap: string; planTitle: string; createdAt: number }>;
    /** ISO timestamp of last profile update */
    updatedAt?: number | string;
    /** Name the user prefers Skales to use */
    preferredName?: string;
}

export interface MasterPlanTask {
    title:       string;
    description: string;
    priority:    TaskPriority;
    tags?:       string[];
    /** If set, a 5-field cron expression — task becomes a recurring cron job */
    schedule?:   string | null;
}

// ─── User Profile ─────────────────────────────────────────────────────────────

function ensureDir() {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
}

export async function loadUserProfile(): Promise<UserProfile> {
    try {
        if (!fs.existsSync(PROFILE_FILE)) return {};
        return JSON.parse(fs.readFileSync(PROFILE_FILE, 'utf-8')) as UserProfile;
    } catch {
        return {};
    }
}

export async function saveUserProfile(profile: UserProfile): Promise<{ success: boolean; error?: string }> {
    try {
        ensureDir();
        const existing = await loadUserProfile();
        const merged   = { ...existing, ...profile, updatedAt: new Date().toISOString() };
        fs.writeFileSync(PROFILE_FILE, JSON.stringify(merged, null, 2));
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Log Management ───────────────────────────────────────────────────────────

export async function getAutopilotLogs(options?: {
    limit?: number;
    taskId?: string;
}): Promise<{ success: boolean; logs?: AutopilotLogEntry[]; error?: string }> {
    try {
        const logs = getLogs({ limit: options?.limit ?? 100, taskId: options?.taskId });
        return { success: true, logs };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function clearAutopilotLogs(): Promise<{ success: boolean; error?: string }> {
    try {
        _clearLogs();
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Task CRUD for Autopilot Dashboard ────────────────────────────────────────

export async function addAutopilotTask(input: {
    title:       string;
    description: string;
    priority?:   TaskPriority;
    tags?:       string[];
    planTitle?:  string;
}): Promise<{ success: boolean; task?: AgentTask; error?: string }> {
    try {
        const task = createTask({
            title:       input.title,
            description: input.description,
            priority:    input.priority ?? 'normal',
            source:      'autopilot',
            tags:        input.tags,
            planTitle:   input.planTitle,
            maxRetries:  3,
        });
        return { success: true, task };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function editAutopilotTask(
    id: string,
    updates: Partial<Pick<AgentTask, 'title' | 'description' | 'priority' | 'tags' | 'planTitle' | 'maxRetries'>>,
): Promise<{ success: boolean; task?: AgentTask | null; error?: string }> {
    try {
        const task = updateTask(id, updates);
        return { success: true, task };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function cancelAutopilotTask(id: string, reason?: string): Promise<{ success: boolean; error?: string }> {
    try {
        cancelTask(id, reason ?? 'Cancelled from Autopilot dashboard');
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function deleteAutopilotTask(id: string): Promise<{ success: boolean; error?: string }> {
    try {
        deleteTask(id);
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function getAutopilotTasks(): Promise<{
    success: boolean;
    tasks?: AgentTask[];
    stats?: ReturnType<typeof getTaskStats>;
    error?: string;
}> {
    try {
        return { success: true, tasks: getAllTasks(), stats: getTaskStats() };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── LLM Helper ───────────────────────────────────────────────────────────────

async function callLLM(settings: any, systemPrompt: string, userMessage: string): Promise<string> {
    const provider = settings?.activeProvider ?? 'openrouter';
    const provCfg  = settings?.providers?.[provider] ?? {};
    const model    = provCfg.model ?? 'gpt-4o';
    const apiKey   = provCfg.apiKey ?? '';

    if (!apiKey) throw new Error(`No API key configured for provider "${provider}".`);

    // Anthropic
    if (provider === 'anthropic') {
        const res = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
            body: JSON.stringify({ model, max_tokens: 2048, system: systemPrompt, messages: [{ role: 'user', content: userMessage }] }),
        });
        if (!res.ok) throw new Error(`Anthropic ${res.status}`);
        const d = await res.json();
        return d.content?.[0]?.text?.trim() ?? '';
    }

    // Google
    if (provider === 'google') {
        const url  = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
        const res  = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ contents: [{ parts: [{ text: systemPrompt + '\n\n' + userMessage }] }] }),
        });
        if (!res.ok) throw new Error(`Google ${res.status}`);
        const d = await res.json();
        return d.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? '';
    }

    // OpenAI-compatible
    const endpoints: Record<string, string> = {
        openrouter: 'https://openrouter.ai/api/v1/chat/completions',
        openai:     'https://api.openai.com/v1/chat/completions',
        groq:       'https://api.groq.com/openai/v1/chat/completions',
        mistral:    'https://api.mistral.ai/v1/chat/completions',
        deepseek:   'https://api.deepseek.com/v1/chat/completions',
        xai:        'https://api.x.ai/v1/chat/completions',
        together:   'https://api.together.xyz/v1/chat/completions',
        ollama:     (provCfg.baseUrl ?? 'http://localhost:11434/v1') + '/chat/completions',
    };
    const url = endpoints[provider] ?? endpoints.openrouter;
    const hdrs: Record<string, string> = { 'Content-Type': 'application/json' };
    if (apiKey && apiKey.trim() !== '') { hdrs['Authorization'] = `Bearer ${apiKey.trim()}`; }
    if (provider === 'openrouter') { hdrs['HTTP-Referer'] = 'https://skales.app'; hdrs['X-Title'] = 'Skales Autopilot'; }

    const res = await fetch(url, {
        method: 'POST',
        headers: hdrs,
        body: JSON.stringify({ model, max_tokens: 2048, temperature: 0.4, messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user',   content: userMessage },
        ]}),
    });
    if (!res.ok) throw new Error(`${provider} ${res.status}: ${await res.text()}`);
    const d   = await res.json();
    const txt = d.choices?.[0]?.message?.content?.trim();
    if (!txt) throw new Error(`Empty response from ${provider}.`);
    return txt;
}

// ─── Deep-Dive Interview ──────────────────────────────────────────────────────

/**
 * Run one turn of the guided Deep-Dive interview.
 * Pass the full conversation history; receives the next AI question or a
 * special COMPLETE marker when enough information has been collected.
 *
 * Returns:
 *   { turn: 'question', message: string }  — follow-up question
 *   { turn: 'complete', profile: UserProfile, summary: string } — interview done
 */
export async function runInterviewTurn(options: {
    history: { role: 'user' | 'assistant'; content: string }[];
    activeSkills?: string[];
}): Promise<{
    success: boolean;
    turn?:   'question' | 'complete';
    message?: string;
    profile?: UserProfile;
    summary?: string;
    error?:   string;
}> {
    try {
        const settings     = await loadSettings();
        const activeSkills = options.activeSkills ?? [];

        const systemPrompt = `You are Skales' Chief-of-Staff AI conducting a strategic Deep-Dive interview to understand the user's goals deeply.

INTERVIEW RULES:
1. Ask ONE focused question at a time. Never multiple questions in one message.
2. Gather: primary goal, niche, budget/resources, constraints, timeline, and any prior attempts.
3. After 4-6 exchanges (when you have enough to build a comprehensive plan), output EXACTLY this JSON block and nothing else:

\`\`\`json
{
  "COMPLETE": true,
  "primaryGoal": "...",
  "niche": "...",
  "budget": "...",
  "constraints": "...",
  "additionalContext": "...",
  "masterPlanSummary": "3-5 sentence strategic overview"
}
\`\`\`

4. Before COMPLETE, respond ONLY with your next interview question as plain text.
5. Be encouraging, direct, and professional. This is a premium feature.
${activeSkills.length ? `\nACTIVE SKILLS (relevant for planning): ${activeSkills.join(', ')}` : ''}`;

        const raw = await callLLM(settings, systemPrompt,
            options.history.map(m => `${m.role === 'user' ? 'User' : 'Skales'}: ${m.content}`).join('\n'),
        );

        // Detect COMPLETE marker
        const jsonMatch = raw.match(/```json\s*([\s\S]*?)```/);
        if (jsonMatch) {
            let parsed: any = {};
            try { parsed = JSON.parse(jsonMatch[1]); } catch { /* ignore */ }

            if (parsed.COMPLETE) {
                const profile: UserProfile = {
                    primaryGoal:       parsed.primaryGoal,
                    niche:             parsed.niche,
                    budget:            parsed.budget,
                    constraints:       parsed.constraints,
                    additionalContext: parsed.additionalContext,
                    masterPlan:        parsed.masterPlanSummary,
                };
                await saveUserProfile(profile);
                return { success: true, turn: 'complete', profile, summary: parsed.masterPlanSummary };
            }
        }

        return { success: true, turn: 'question', message: raw.replace(/```json[\s\S]*?```/g, '').trim() };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Master Plan Generation ────────────────────────────────────────────────────

/**
 * Generate a Master Plan from the user's profile + active skills.
 * Breaks it into actionable sub-tasks and pushes them to tasks.json.
 *
 * Returns the list of created tasks + a high-level roadmap string.
 */
export async function generateMasterPlan(options?: {
    activeSkills?: string[];
    overrideGoal?: string;
}): Promise<{
    success:   boolean;
    tasks?:    AgentTask[];
    roadmap?:  string;
    planTitle?: string;
    error?:    string;
}> {
    try {
        const settings = await loadSettings();
        const profile  = await loadUserProfile();
        const goal     = options?.overrideGoal ?? profile.primaryGoal ?? 'Build a successful online business';
        const skills   = options?.activeSkills ?? [];

        const systemPrompt = `You are Skales' strategic AI planner. Your job is to generate a deterministic, actionable Master Plan.

USER PROFILE:
Goal: ${goal}
Niche: ${profile.niche ?? 'not specified'}
Budget: ${profile.budget ?? 'not specified'}
Constraints: ${profile.constraints ?? 'none'}
Context: ${profile.additionalContext ?? 'none'}

AVAILABLE SKILLS: ${skills.length ? skills.join(', ') : 'standard (chat, file management, web search)'}

OUTPUT FORMAT (respond with ONLY valid JSON — no markdown fences, no extra text):
{
  "planTitle": "Short 5-word plan name",
  "roadmap": "3-5 sentence high-level strategy",
  "tasks": [
    {
      "title": "Concise action title (max 80 chars)",
      "description": "Detailed instructions for the AI agent executing this task",
      "priority": "high|normal|low",
      "tags": ["tag1", "tag2"],
      "schedule": null
    }
  ]
}

For each task, decide if it is ONE-TIME or RECURRING.
- ONE-TIME tasks: set "schedule": null
- RECURRING tasks: set "schedule" to a standard 5-field cron expression.
  Examples:
    "0 8 * * *"     = every day at 8:00 AM
    "0 9 * * 1"     = every Monday at 9:00 AM
    "*/30 * * * *"  = every 30 minutes
    "0 8,18 * * *"  = every day at 8:00 AM and 6:00 PM
    "0 9 * * 1-5"   = every weekday at 9:00 AM

RULES:
- Generate 5-12 concrete, executable tasks ordered by logical sequence
- Each task must be completable by an AI agent without human input (or clearly state what human input is needed)
- Do NOT repeat tasks. Be specific, not vague.
- Tasks must directly serve the stated goal.
- If the goal implies daily/weekly/recurring work (monitoring, reporting, checking), use "schedule" with the appropriate cron expression.`;

        const raw = await callLLM(settings, systemPrompt, `Generate a complete Master Plan to: ${goal}`);

        // Parse JSON — strip any accidental markdown fences
        const cleaned = raw.replace(/^```json\s*/i, '').replace(/```\s*$/, '').trim();
        let parsed: any;
        try {
            parsed = JSON.parse(cleaned);
        } catch {
            // Attempt to extract JSON with regex
            const m = raw.match(/\{[\s\S]*\}/);
            if (!m) throw new Error('LLM did not return valid JSON for the Master Plan.');
            parsed = JSON.parse(m[0]);
        }

        const planTitle: string = parsed.planTitle ?? 'Master Plan';
        const roadmap:   string = parsed.roadmap   ?? '';
        const rawTasks: MasterPlanTask[] = Array.isArray(parsed.tasks) ? parsed.tasks : [];

        // Push tasks into tasks.json (one-shot) or cron_jobs (recurring)
        const created: AgentTask[] = [];
        let cronJobsCreated = 0;
        for (const t of rawTasks) {
            if (!t.title || !t.description) continue;

            // Recurring task → create a cron job instead of a one-shot task
            if (t.schedule && typeof t.schedule === 'string' && /^\S+\s+\S+\s+\S+\s+\S+\s+\S+$/.test(t.schedule.trim())) {
                try {
                    const { createCronJob } = await import('@/actions/tasks');
                    await createCronJob({
                        name:     t.title.slice(0, 200),
                        schedule: t.schedule.trim(),
                        task:     t.description,
                        enabled:  true,
                    });
                    cronJobsCreated++;
                } catch (cronErr: any) {
                    console.warn(`[MasterPlan] Failed to create cron job for "${t.title}":`, cronErr?.message);
                    // Fallback: create as one-shot task
                    const task = createTask({
                        title:       t.title.slice(0, 200),
                        description: t.description,
                        priority:    t.priority ?? 'normal',
                        source:      'autopilot',
                        tags:        t.tags ?? [],
                        planTitle,
                        maxRetries:  3,
                    });
                    created.push(task);
                }
            } else {
                // One-shot task (existing behavior)
                const task = createTask({
                    title:       t.title.slice(0, 200),
                    description: t.description,
                    priority:    t.priority ?? 'normal',
                    source:      'autopilot',
                    tags:        t.tags ?? [],
                    planTitle,
                    maxRetries:  3,
                });
                created.push(task);
            }
        }

        // Archive previous roadmap before overwriting
        try {
            const { loadUserProfile } = await import('./autopilot');
            const existing = await loadUserProfile();
            if (existing?.masterPlan) {
                const history: Array<{ roadmap: string; planTitle: string; createdAt: number }> =
                    Array.isArray(existing.roadmapHistory) ? existing.roadmapHistory : [];
                history.unshift({ roadmap: existing.masterPlan, planTitle: existing.masterPlanTitle || 'Plan', createdAt: typeof existing.updatedAt === 'number' ? existing.updatedAt : Date.now() });
                // Keep max 10 historical entries
                await saveUserProfile({ roadmapHistory: history.slice(0, 10), masterPlanTitle: planTitle });
            } else {
                await saveUserProfile({ masterPlanTitle: planTitle });
            }
        } catch { /* non-fatal — history tracking is best-effort */ }

        // Persist new roadmap to profile
        await saveUserProfile({ masterPlan: roadmap });

        const { log } = await import('@/lib/autopilot-logger');
        const cronNote = cronJobsCreated > 0 ? ` + ${cronJobsCreated} recurring schedule(s)` : '';
        log.success('plan_created', `🗺️ Master Plan "${planTitle}" created with ${created.length} tasks${cronNote}.`, {
            detail: { planTitle, taskCount: created.length, cronJobsCreated },
        });

        return { success: true, tasks: created, roadmap, planTitle };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Daily Stand-Up Report ────────────────────────────────────────────────────

/**
 * Generate a concise stand-up report of what the agent did + what's blocked.
 * Returns a markdown string suitable for display in the chat or dashboard.
 */
export async function generateStandupReport(): Promise<{
    success: boolean;
    report?: string;
    hasBlockedTasks?: boolean;
    error?: string;
}> {
    try {
        const settings = await loadSettings();
        const tasks    = getAllTasks();
        const logs     = getLogs({ limit: 50 });

        const completed = tasks.filter(t => t.state === 'completed').slice(0, 10);
        const blocked   = tasks.filter(t => t.state === 'blocked');
        const pending   = tasks.filter(t => t.state === 'pending');

        if (completed.length === 0 && blocked.length === 0) {
            return { success: true, report: 'No completed or blocked tasks to report.', hasBlockedTasks: false };
        }

        const systemPrompt = `You are Skales generating a crisp daily stand-up report for the user.
Write in first person ("I completed...", "I am blocked on...").
Be friendly but professional. Use bullet points. Keep it under 200 words.
End with a clear question if there are blocked tasks.`;

        const userMessage = `
COMPLETED TASKS (${completed.length}):
${completed.map(t => `• ${t.title}: ${(t.result ?? '').slice(0, 150)}`).join('\n') || 'None'}

BLOCKED TASKS (${blocked.length}):
${blocked.map(t => `• ${t.title}: ${t.blockedReason ?? t.error ?? 'Unknown reason'}`).join('\n') || 'None'}

PENDING TASKS (${pending.length}):
${pending.slice(0, 5).map(t => `• ${t.title} [${t.priority}]`).join('\n') || 'None'}

RECENT LOG ACTIVITY:
${logs.slice(0, 5).map(l => `• ${l.timestamp.slice(11, 16)} — ${l.message}`).join('\n') || 'None'}

Generate the stand-up report now.`;

        const report = await callLLM(settings, systemPrompt, userMessage);

        const { log } = await import('@/lib/autopilot-logger');
        log.info('standup_generated', `📋 Daily stand-up generated.`, { detail: { blockedCount: blocked.length, completedCount: completed.length } });

        return { success: true, report, hasBlockedTasks: blocked.length > 0 };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Morning Briefing ─────────────────────────────────────────────────────────

/**
 * Generate a personalised morning briefing delivered via Telegram (if configured)
 * and returned as a markdown string for display in the dashboard.
 *
 * Sections (graceful degrades if data unavailable):
 *   1. Greeting + date/time
 *   2. Today's calendar events (try/catch — optional integration)
 *   3. Pending & in-progress tasks
 *   4. Unread email count (try/catch — optional integration)
 *   5. Closing motivational question from the LLM
 */
export async function generateMorningBriefing(): Promise<{
    success: boolean;
    briefing?: string;
    deliveredViaTelegram?: boolean;
    error?: string;
}> {
    try {
        const settings = await loadSettings();
        const tasks    = getAllTasks();

        // ── Gather context sections ──────────────────────────────────────────

        const now      = new Date();
        const dateStr  = now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
        const timeStr  = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

        // Pending / in-progress tasks
        const pending    = tasks.filter(t => t.state === 'pending').slice(0, 8);
        const inProgress = tasks.filter(t => t.state === 'running').slice(0, 3);
        const blocked    = tasks.filter(t => t.state === 'blocked');

        // Calendar events — optional (no getCalendarEventsToday yet)
        let calendarLines = '(Calendar integration not configured)';
        try {
            // @ts-ignore — dynamic import in case calendar module ships later
            const { getCalendarEventsToday } = await import('@/actions/calendar');
            const events: Array<{ time: string; title: string }> = await getCalendarEventsToday();
            if (events.length === 0) {
                calendarLines = 'No events scheduled for today.';
            } else {
                calendarLines = events.map(e => `• ${e.time} — ${e.title}`).join('\n');
            }
        } catch { /* calendar not available */ }

        // Unread email count — optional
        let emailLines = '(Email integration not configured)';
        try {
            // @ts-ignore — dynamic import in case email count helper ships later
            const { getUnreadEmailCount } = await import('@/actions/email');
            const count: number = await getUnreadEmailCount();
            emailLines = count === 0 ? 'Inbox zero! 🎉' : `${count} unread message${count !== 1 ? 's' : ''} waiting.`;
        } catch { /* email not available */ }

        // ── Build LLM prompt ─────────────────────────────────────────────────

        const systemPrompt = `You are Skales generating a warm, upbeat morning briefing for the user.
Write in second person ("You have...", "Today looks...").
Be concise, friendly, and motivating. Use light markdown (bold for key items, bullet points).
Keep it under 250 words. End with one short, encouraging question to help the user focus.`;

        const userMessage = `
TODAY: ${dateStr} at ${timeStr}

CALENDAR EVENTS:
${calendarLines}

TASKS IN PROGRESS (${inProgress.length}):
${inProgress.map(t => `• ${t.title}`).join('\n') || 'None'}

PENDING TASKS (${pending.length} shown):
${pending.map(t => `• ${t.title} [${t.priority ?? 'normal'}]`).join('\n') || 'None'}

BLOCKED TASKS (${blocked.length}):
${blocked.map(t => `• ${t.title}: ${t.blockedReason ?? 'Unknown reason'}`).join('\n') || 'None'}

EMAILS:
${emailLines}

Generate the morning briefing now.`;

        const briefing = await callLLM(settings, systemPrompt, userMessage);

        // ── Deliver via Telegram if configured ───────────────────────────────

        let deliveredViaTelegram = false;
        try {
            const { loadTelegramConfig, sendMessage } = await import('@/actions/telegram');
            const tgCfg = await loadTelegramConfig();
            if (tgCfg?.token && tgCfg?.chatId) {
                const header = `☀️ *Good morning — ${dateStr}*\n\n`;
                await sendMessage(tgCfg.token, tgCfg.chatId, header + briefing);
                deliveredViaTelegram = true;
            }
        } catch { /* non-fatal — Telegram may not be configured */ }

        const { log } = await import('@/lib/autopilot-logger');
        log.success('briefing_generated', `☀️ Morning briefing generated.`, {
            detail: { pendingCount: pending.length, blockedCount: blocked.length, deliveredViaTelegram },
        });

        return { success: true, briefing, deliveredViaTelegram };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Task Approval (Human-in-the-Loop) ───────────────────────────────────────

export async function approveAutopilotTask(id: string): Promise<{ success: boolean; error?: string }> {
    try {
        const { approveTask } = await import('@/lib/agent-tasks');
        const { log } = await import('@/lib/autopilot-logger');
        approveTask(id);
        log.info('task_started', `✅ Task approved by user.`, { taskId: id });
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function rejectAutopilotTask(id: string, reason?: string): Promise<{ success: boolean; error?: string }> {
    try {
        const { rejectTask } = await import('@/lib/agent-tasks');
        const { log } = await import('@/lib/autopilot-logger');
        rejectTask(id, reason);
        log.warning('task_cancelled', `❌ Task rejected by user: ${reason ?? 'No reason given'}.`, { taskId: id });
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

/**
 * Retry a blocked task — resets it back to 'pending' so the runner picks it up
 * again on the next tick. Also clears blockedReason and resets retryCount.
 */
export async function retryBlockedTask(id: string): Promise<{ success: boolean; error?: string }> {
    try {
        const { updateTask, getTask } = await import('@/lib/agent-tasks');
        const { log } = await import('@/lib/autopilot-logger');
        const task = getTask(id);
        if (!task) return { success: false, error: 'Task not found' };
        if (task.state !== 'blocked' && task.state !== 'failed') {
            return { success: false, error: `Task is in state '${task.state}', not blocked/failed` };
        }
        updateTask(id, {
            state:         'pending',
            blockedReason: undefined,
            retryCount:    0,
            result:        undefined,
        });
        log.info('task_started', `🔄 Task manually retried by user.`, { taskId: id });
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── OODA Re-Planner ─────────────────────────────────────────────────────────

/**
 * Autonomous re-planning: the agent discovered new context and needs to
 * rewrite/reprioritize/delete pending tasks in tasks.json.
 *
 * Called by the skill-dispatcher's ooda_replan handler.
 */
export async function replanTasksFromContext(options: {
    newContext: string;
    planTitle?: string;
}): Promise<{ success: boolean; summary?: string; changes?: any[]; error?: string }> {
    try {
        const settings = await loadSettings();
        const allTasks = getAllTasks();
        const pending  = allTasks.filter(t => t.state === 'pending');

        if (pending.length === 0) {
            return { success: true, summary: 'No pending tasks to re-plan.', changes: [] };
        }

        const systemPrompt = `You are Skales Autopilot's OODA (Observe-Orient-Decide-Act) re-planner.
New critical context has been discovered that may invalidate or change the current task plan.
Analyze the context and decide which pending tasks to: UPDATE, DELETE, or REPRIORITIZE.

NEW CONTEXT:
${options.newContext}

CURRENT PENDING TASKS:
${pending.map((t, i) => `${i + 1}. [${t.id.slice(0, 8)}] "${t.title}" [${t.priority}]:\n   ${t.description.slice(0, 200)}`).join('\n')}

OUTPUT: Respond with ONLY a JSON array of change directives. Each directive:
{
  "taskId": "first 8 chars of task id",
  "action": "update" | "delete" | "reprioritize",
  "newTitle": "optional new title (for update)",
  "newDescription": "optional new description (for update)",
  "newPriority": "high|normal|low (for reprioritize)",
  "reason": "why this change is needed"
}

If no changes are needed, output: []`;

        const raw = await callLLM(settings, systemPrompt,
            `Re-plan based on this new context: ${options.newContext.slice(0, 500)}`);

        let directives: any[] = [];
        try {
            const cleaned = raw.replace(/^```json\s*/i, '').replace(/```\s*$/, '').trim();
            directives = JSON.parse(cleaned);
            if (!Array.isArray(directives)) directives = [];
        } catch { /* no re-plan needed */ }

        const changes: any[] = [];
        const { log } = await import('@/lib/autopilot-logger');

        for (const d of directives) {
            // Find the full task ID by prefix match
            const task = pending.find(t => t.id.startsWith(d.taskId));
            if (!task) continue;

            if (d.action === 'delete') {
                deleteTask(task.id);
                changes.push({ taskId: task.id, action: 'deleted', reason: d.reason });
                log.warning('plan_created', `🗑️ OODA: Deleted task "${task.title}" — ${d.reason}`, { taskId: task.id });

            } else if (d.action === 'update') {
                updateTask(task.id, {
                    title:       d.newTitle       ?? task.title,
                    description: d.newDescription ?? task.description,
                    replanReason: d.reason,
                    replannedAt:  new Date().toISOString(),
                });
                changes.push({ taskId: task.id, action: 'updated', reason: d.reason });
                log.warning('plan_created', `✏️ OODA: Updated task "${task.title}" — ${d.reason}`, { taskId: task.id });

            } else if (d.action === 'reprioritize') {
                updateTask(task.id, {
                    priority:     d.newPriority ?? task.priority,
                    replanReason: d.reason,
                    replannedAt:  new Date().toISOString(),
                });
                changes.push({ taskId: task.id, action: 'reprioritized', newPriority: d.newPriority, reason: d.reason });
                log.info('plan_created', `🔀 OODA: Reprioritized "${task.title}" → ${d.newPriority} — ${d.reason}`, { taskId: task.id });
            }
        }

        const summary = changes.length > 0
            ? `OODA re-plan: ${changes.length} change(s) made — ${changes.map(c => `${c.action} "${c.taskId.slice(0, 8)}"`).join(', ')}`
            : 'No task changes needed based on new context.';

        return { success: true, summary, changes };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

// ─── Cost Control Settings ────────────────────────────────────────────────────

export async function saveAutopilotConfig(config: {
    maxCallsPerHour?: number;
    pauseAfterTasks?: number;
}): Promise<{ success: boolean; error?: string }> {
    try {
        const { saveAllSettings, loadSettings } = await import('@/actions/chat');
        const settings = await loadSettings();
        await saveAllSettings({ ...settings, autopilotConfig: { ...((settings as any).autopilotConfig ?? {}), ...config } } as any);
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}

export async function resumeFromCostPause(): Promise<{ success: boolean; error?: string }> {
    try {
        const { resumeFromCostPause: runnerResume } = await import('@/lib/autonomous-runner');
        runnerResume();
        return { success: true };
    } catch (e: any) {
        return { success: false, error: e.message };
    }
}
